version: '3.8'

services:
  trans-nusa-app:
    image: sungaibudiwebdev/trans-anugerah-nusa:latest
    container_name: trans-nusa-app
    restart: unless-stopped
    depends_on:
      - trans-nusa-db
    env_file:
      - .env
    volumes:
      - ./storage:/var/www/html/storage
      - ./docker/nginx/default.conf:/etc/nginx/http.d/default.conf:ro
    networks:
      - web-network      # Jalur ke Satpam Depan
      - trans-nusa-internal # Jalur ke Database

  trans-nusa-db:
    image: mysql:8.0
    container_name: trans-nusa-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - trans-nusa-internal

networks:
  web-network:
    external: true
  trans-nusa-internal:
    driver: bridge